language: node_js
node_js: "stable"

cache:
  yarn: true
  directories: 
  - node_modules

script:
  - yarn
  - yarn doc:build

# Deploy to surge
deploy:
  provider: surge
  project: docs-build
  domain: https://fun-with-docz.surge.sh